# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafioContaStone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafioContaStone
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'desafioContaStoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafioContaStoneUITests' do
    # Pods for testing
  end

end
